version: '3.8'
services:
  discord-bot:
    build:
      context: .  # <- Isso garante que a imagem seja construída do Dockerfile local
    image: discord-bot-ninja
    environment:
      - DISCORD_TOKEN
    restart: always
